version: '3.9'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: "engsoft"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "1234567"
    ports:
      - "5432:5432"

  api: 
    env_file:
      - .env
    depends_on:
      - db
    build: ./
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/app
      - /home/app/node_modules